const menu = [
  {
    id: 1,
    title: 'The Krusty Burger',
    category: 'burger',
    price: 15.99,
    img: '/images/krusty-burger.webp',
    desc: `The fictional Simpsons hangout was so popular, it became a real-life restaurant in 2013, when Universal Studios Orlando opened a Simpsons theme park. Ironically, menu staples like the Clogger Burger and the Mother Nature Burger—dismissed as gross on the cartoon—fetch over $10 in real life.`,
  },
  {
    id: 2,
    title: 'The Umami Burger',
    category: 'burger',
    price: 13.99,
    img: '/images/umami-burger.webp',
    desc: `Arguably the first “modernist cuisine” patty, the Umami Burger—unveiled by Adam Fleischman in 2009—is meant to taste like, well, umami (a savory taste embodied in MSG), incorporating such toppings as soy-roasted tomatoes, parmesan crisps and pickled ginger. The patty’s success has fueled the opening of 21 additional locations. `,
  },
  {
    id: 3,
    title: 'The Quadruple',
    category: 'burger',
    price: 26.99,
    img: '/images/quad.webp',
    desc: `Jon Basso, owner of The Heart Attack Grill, has drawn national attention (and outrage) for his gluttonous offerings since the restaurant first opened in 2005, offering free meals for those over 350 pounds. His most notorious dish is this behemoth, which layers eight slices of cheese between four half-pound patties and clocks in at nearly 10,000 calories`,
  },
  {
    id: 4,
    title: 'The 21 burger',
    category: 'burger',
    price: 12.99,
    img: '/images/21-burger.webp',
    desc: `When the 21 Club introduced its gourmet burger in the late 1940s or early 1950s, New Yorkers were shocked that an upper-class establishment would offer something as lowly as the burger—and at the exorbitant price of $2.75, compared with McDonalds 15 cents. `,
  },
  {
    id: 5,
    title: 'Chicago deep dish',
    category: 'pizza',
    price: 22.99,
    img: '/images/chicago.webp',
    desc: `Much like with its baseball teams, Chicago also has two distinct styles of pizza. And though the rivalry isn't quite as divisive as that between the Cubs and the White Sox, people in the Windy City definitely have their opinions on pizza, too. `,
  },
  {
    id: 6,
    title: 'Tavern style',
    category: 'pizza',
    price: 18.99,
    img:'/images/tavern.webp',
    desc: `The far more frequent choice for discerning Chicagoans is the thin crust or tavern-style pizza. Bon Appétit went so far as to call it "Chicago's real signature pizza," citing everyone from local food authors to pizza tour guides who claim this is the style locals identify with most.`,
  },
  {
    id: 7,
    title: 'Neopolitan',
    category: 'pizza',
    price: 8.99,
    img: '/images/neapolitan.webp',
    desc: `As the gourmet pizza restaurant has become a staple of the food scene in pretty much every American city, by and large people have become well educated in Neapolitan-style pies. We can recognize Neapolitan-style pizzas by the char out the outside of the crispy crust, as well as the thin, sometimes soggy center of the pizza, and the fresh mozzarella cheese on top.`,
  },
  {
    id: 8,
    title: 'Sorbet',
    category: 'ice-creams',
    price: 6.99,
    img: '/images/sorbet.jpeg',
    desc: `Sorbetes is a popular Filipino ice cream flavored with ingredients such as mango, chocolate, cheese, coconut, and purple yam (ube). Traditionally, it is produced from carabao milk and served in tiny scoops on sugar cones. `,
  },
  {
    id: 9,
    title: 'Gelato al pista',
    category: 'ice-creams',
    price: 9.99,
    img: '/images/gelato.jpeg',
    desc: `Pistachio is one of the most popular flavors of Italian gelato. A mainstay in every gelateria, in its original form, this frozen treat combines pistachio paste with the classic base of milk, cream, eggs, and sugar.`,
  },
];
export default menu;
